connector.class=io.debezium.connector.postgresql.PostgresConnector
transforms.unwrap.delete.handling.mode=rewrite
max.queue.size=8192
slot.name=debezium_slot
tasks.max=1
publication.name=my_cdc_pub
transforms=unwrap
schema.include.list=gaming_oltp
tombstones.on.delete=true
database.sslmode=require
topic.prefix=cdc-gaming
decimal.handling.mode=double
transforms.unwrap.drop.tombstones=false
poll.interval.ms=1000
interval.handling.mode=string
transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
heartbeat.topics.prefix=__debezium-heartbeat
errors.retry.delay.initial.ms=300
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter=org.apache.kafka.connect.storage.StringConverter
errors.retry.timeout=300000
database.user=postgres
database.dbname=postgres
time.precision.mode=adaptive_time_microseconds
database.server.name=gaming
errors.retry.delay.max.ms=10000
heartbeat.interval.ms=30000
database.port=5432
plugin.name=pgoutput
database.hostname=cdc-scd2-gaming-app-cluster.c2hosmioqybn.us-east-1.rds.amazonaws.com
database.password=shihab1327&
value.converter.schemas.enable=true
transforms.unwrap.add.fields=op,ts_ms,source.ts_ms,source.lsn
max.batch.size=2048
snapshot.mode=initial